# Generated by Django 4.2.5 on 2023-11-04 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_registration_alter_book_id_alter_bus_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
