# Generated by Django 4.2.5 on 2024-01-24 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_refund_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refund',
            name='status',
            field=models.CharField(choices=[('R', 'Refunded'), ('NR', 'Not Refunded')], default='NR', max_length=2),
        ),
    ]
